---
title: "Third_process"
author: "Michael Pearson"
date: "9/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr, quietly = TRUE)
library(readr, quietly = TRUE)
library(R.utils, quietly = TRUE)
library(SnowballC, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(data.table, quietly = TRUE)
```

## R Markdown

Do the combi thing

```{r combi}
bi_bigrams <-  read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/bi_bigrams.csv" , colClasses = c("NULL", NA, NA, NA))
##bi_bigrams <- bi_bigrams[,2:4]
bi_bigrams <- data.table(bi_bigrams)
tri_trigrams <- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/tri_trigrams.csv",colClasses = c("NULL", NA, NA, NA, NA) )
##tri_trigrams <- tri_trigrams[,2:5]
tri_trigrams <- data.table(tri_trigrams)
combi_tri <- unite(tri_trigrams, bigrams, c("word1", "word2"), sep = " ")
rm(tri_trigrams)
write.csv(combi_tri,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_trigrams.csv" )
rm(combi_tri)
sen_tri_trigrams <- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/sen_tri_trigrams.csv",colClasses = c("NULL", NA, NA, NA, NA) )
sen_tri_trigrams <- data.table(sen_tri_trigrams)
combi_sen_tri <- unite(sen_tri_trigrams, bigrams, c("word1", "word2"), sep = " ")
rm(sen_tri_trigrams)
write.csv(combi_sen_tri,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_sen_tri.csv" )
rm(combi_sen_tri)
quad_quadgrams <- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/quad_quadgrams.csv",colClasses = c("NULL", NA, NA, NA, NA,NA) )
quad_quadgrams <- data.table(quad_quadgrams)
combi_quad <- unite(quad_quadgrams, trigrams, c("word1", "word2", "word3"), sep = " ")
rm(quad_quadgrams)
write.csv(combi_quad,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_quad.csv" )
rm(combi_quad)
sen_quad_quadgrams<- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/sen_quad_quadgrams.csv",colClasses = c("NULL", NA, NA, NA, NA,NA) )
sen_quad_quadgrams <- data.table(sen_quad_quadgrams)
combi_sen_quad <- unite(sen_quad_quadgrams, trigrams, c("word1", "word2","word3"), sep = " ")
rm(sen_quad_quadgrams)
write.csv(combi_sen_quad,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_sen_quad.csv" )
rm(combi_sen_quad)
quin_quingrams <- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/quin_quingrams.csv",colClasses = c("NULL", NA, NA, NA, NA,NA,NA) )
quin_quingrams <- data.table(quin_quingrams)
combi_quin <- unite(quin_quingrams, quadgrams, c("word1", "word2", "word3","word4"), sep = " ")
rm(quin_quingrams)
write.csv(combi_quin,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_quin.csv" )
rm(combi_quin)
sen_quin_quingrams<- read.csv(file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/sen_quin_quingrams.csv",colClasses = c("NULL", NA, NA, NA, NA,NA,NA) )
sen_quin_quingrams <- data.table(sen_quin_quingrams)
combi_sen_quin <- unite(sen_quin_quingrams, quadgrams, c("word1", "word2","word3", "word4"), sep = " ")
rm(sen_quin_quingrams)
write.csv(combi_sen_quin,file = "/Users/mutecypher/Documents/Documents - Michael’s iMac/Coursera/Capstone Project/processed/combi_sen_quin.csv" )
rm(combi_sen_quin)
```

## Including Stuff at the end

You can also embed plots, for example:


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
